# Generated by Django 4.0.3 on 2022-03-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='skills',
        ),
    ]
