# Generated by Django 4.0.3 on 2022-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_company_contact_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=17),
        ),
    ]
