# Generated by Django 4.0.3 on 2022-03-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_company_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_pic',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
