# Generated by Django 4.0.3 on 2022-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
