# Generated by Django 4.0.3 on 2022-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_delete_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
