# Generated by Django 4.0.3 on 2022-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verification',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
