# Generated by Django 4.0.3 on 2022-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_company_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_verification',
            field=models.FileField(default=11, upload_to='media/'),
            preserve_default=False,
        ),
    ]
