# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_mycustomuser_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_verification',
        ),
        migrations.RemoveField(
            model_name='company',
            name='verification',
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='verification',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
